USE VuelosDB;
GO

DROP TABLE IF EXISTS Flights_Fact;
GO
DROP TABLE IF EXISTS Passengers_Dim;
GO
DROP TABLE IF EXISTS Airports_Dim;
GO
DROP TABLE IF EXISTS Pilots_Dim;
GO
DROP TABLE IF EXISTS Dates_Dim;
GO
DROP TABLE IF EXISTS FlightStatus_Dim;
GO